import type { Metadata } from "next";
import "./globals.scss";
import NavigationbarWrapper from "./components/NavigationbarWrapper/NavigationbarWrapper";

export const metadata: Metadata = {
  title: "البضاعه | Goods - Your Comprehensive Goods Marketplace",
  description: "Generated by create next app",
};


export default function RootLayout({
       children,
       }: Readonly<{
              children: React.ReactNode;
       }>) {
       return (
       <html lang="en">
       <body>
              <NavigationbarWrapper />
              {children}
       </body>
       </html>
       );
}
