export const cites = [
       {id:0,governorate_name_ar:"جميع المحافظات",governorate_name_en:"All cites"},
       {id:1,governorate_name_ar:"محافظه القاهرة",governorate_name_en:"Cairo"},
       {id:2,governorate_name_ar:"محافظه الجيزة",governorate_name_en:"Giza"},
       {id:3,governorate_name_ar:"محافظه الأسكندرية",governorate_name_en:"Alexandria"},
       {id:4,governorate_name_ar:"محافظه الدقهلية",governorate_name_en:"Dakahlia"},
       {id:5,governorate_name_ar:"محافظه البحر الأحمر",governorate_name_en:"Red Sea"},
       {id:6,governorate_name_ar:"محافظه البحيرة",governorate_name_en:"Beheira"},
       {id:7,governorate_name_ar:"محافظه الفيوم",governorate_name_en:"Fayoum"},
       {id:8,governorate_name_ar:"محافظه الغربية",governorate_name_en:"Gharbiya"},
       {id:9,governorate_name_ar:"محافظه الإسماعلية",governorate_name_en:"Ismailia"},
       {id:10,governorate_name_ar:"محافظه المنوفية",governorate_name_en:"Menofia"},
       {id:11,governorate_name_ar:"محافظه المنيا",governorate_name_en:"Minya"},
       {id:12,governorate_name_ar:"محافظه القليوبية",governorate_name_en:"Qaliubiya"},
       {id:13,governorate_name_ar:"محافظه الوادي الجديد",governorate_name_en:"New Valley"},
       {id:14,governorate_name_ar:"محافظه السويس",governorate_name_en:"Suez"},
       {id:15,governorate_name_ar:"محافظه اسوان",governorate_name_en:"Aswan"},
       {id:16,governorate_name_ar:"محافظه اسيوط",governorate_name_en:"Assiut"},
       {id:17,governorate_name_ar:"محافظه بني سويف",governorate_name_en:"Beni Suef"},
       {id:18,governorate_name_ar:"محافظه بورسعيد",governorate_name_en:"Port Said"},
       {id:19,governorate_name_ar:"محافظه دمياط",governorate_name_en:"Damietta"},
       {id:20,governorate_name_ar:"محافظه الشرقية",governorate_name_en:"Sharkia"},
       {id:21,governorate_name_ar:"محافظه جنوب سيناء",governorate_name_en:"South Sinai"},
       {id:22,governorate_name_ar:"محافظه كفر الشيخ",governorate_name_en:"Kafr Al sheikh"},
       {id:23,governorate_name_ar:"محافظه مطروح",governorate_name_en:"Matrouh"},
       {id:24,governorate_name_ar:"محافظه الأقصر",governorate_name_en:"Luxor"},
       {id:25,governorate_name_ar:"محافظه قنا",governorate_name_en:"Qena"},
       {id:26,governorate_name_ar:"محافظه شمال سيناء",governorate_name_en:"North Sinai"},
       {id:27,governorate_name_ar:"محافظه سوهاج",governorate_name_en:"Sohag"}
]